"""L5 — provenance.

Every action appends an event here, and the log exports as a runnable Python
script. This is what makes a number on screen defensible: you can trace it back
through the filters, transforms and queries that produced it, and re-run them.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone

import pandas as pd


@dataclass
class Event:
    kind: str
    summary: str
    payload: dict = field(default_factory=dict)
    at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds"))


class Provenance:
    """Append-only session log."""

    def __init__(self) -> None:
        self.events: list[Event] = []

    def record(self, kind: str, summary: str, **payload) -> Event:
        event = Event(kind=kind, summary=summary, payload=payload)
        self.events.append(event)
        return event

    def clear(self) -> None:
        self.events.clear()

    def frame(self) -> pd.DataFrame:
        return pd.DataFrame(
            [{"at": e.at, "step": i + 1, "kind": e.kind, "action": e.summary} for i, e in enumerate(self.events)]
        )

    def to_json(self) -> str:
        return json.dumps(
            [{"at": e.at, "kind": e.kind, "summary": e.summary, "payload": e.payload} for e in self.events],
            indent=2,
            default=str,
        )

    def to_script(self, table: str = "dataset") -> str:
        """Render the session as a standalone Python script that reproduces it."""
        lines = [
            '"""Reproduces this analysis session.',
            "",
            f"Generated by Groundtruth at {datetime.now(timezone.utc).isoformat(timespec='seconds')}.",
            f"{len(self.events)} recorded step(s).",
            '"""',
            "import duckdb",
            "import pandas as pd",
            "",
            "con = duckdb.connect()",
            "",
        ]
        for index, event in enumerate(self.events, start=1):
            lines.append(f"# --- Step {index}: {event.summary} ---")
            payload = event.payload

            if event.kind == "load" and payload.get("path"):
                lines.append(f"df = pd.read_csv({payload['path']!r})" if str(payload["path"]).endswith(".csv")
                             else f"df = pd.read_parquet({payload['path']!r})")
                lines.append(f"con.register({table!r}, df)")
            elif event.kind == "load":
                lines.append(f"# source: {payload.get('detail', 'unknown')}")
                lines.append(f"# df = ...  # reload {payload.get('rows', '?')} rows from this source")
                lines.append(f"con.register({table!r}, df)")
            elif event.kind == "filter":
                where = payload.get("where", "")
                params = payload.get("params", [])
                if where:
                    lines.append(f"where = {where!r}")
                    lines.append(f"params = {params!r}")
                    lines.append(f'filtered = con.execute(f"SELECT * FROM {table} WHERE {{where}}", params).fetch_df()')
                else:
                    lines.append(f'filtered = con.execute("SELECT * FROM {table}").fetch_df()')
            elif event.kind == "transform":
                lines.append(f"con.execute({payload.get('sql', '')!r})")
            elif event.kind in ("query", "agent_sql"):
                lines.append(f"result = con.execute({payload.get('sql', '')!r}).fetch_df()")
                lines.append("print(result)")
            elif event.kind == "stat_test":
                lines.append(f"# {payload.get('test', '')}: {payload.get('result', '')}")
            elif event.kind == "model":
                lines.append(f"# target={payload.get('target')!r} features={payload.get('features')}")
                lines.append(f"# best model: {payload.get('best_model')} | {payload.get('metrics')}")
            elif event.kind == "chart":
                lines.append(f"# chart: {payload.get('spec', '')}")
            elif event.kind == "question":
                lines.append(f"# asked: {payload.get('question', '')}")
                for sql in payload.get("queries", []):
                    lines.append(f"result = con.execute({sql!r}).fetch_df()")
            else:
                lines.append(f"# {event.summary}")
            lines.append("")
        return "\n".join(lines)

    def to_markdown(self) -> str:
        rows = ["# Analysis lineage", ""]
        for index, event in enumerate(self.events, start=1):
            rows.append(f"{index}. **{event.kind}** — {event.summary}  \n   _{event.at}_")
        return "\n".join(rows)
